# Generated by Django 5.0.6 on 2025-03-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 speakers per team'), (3, '3 speakers per team')], default=3),
        ),
    ]
