# Generated by Django 5.0.6 on 2025-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_speaker_score',
            field=models.FloatField(default=79.0, help_text='Maximum speaker score allowed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_speaker_score',
            field=models.FloatField(default=69.0, help_text='Minimum speaker score allowed'),
        ),
    ]
