services:
  - type: web
    name: tabbycat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn debateTab.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: debateTab.production_settings
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: tabbycat-db
          property: connectionString

databases:
  - name: tabbycat-db
    databaseName: tabbycat
    user: tabbycat_user 